### ISSUE TITLE
Running Redshift COPY command from JDBC

### ISSUE THREAD

**Issue by bitbythecron** [albfan/sqlworkbenchj#16]
Hey I'm trying to execute a Redshift COPY command right from inside a Java app using JDBC (Postgres driver). I'm having issues where the JDBC `Statement` seems to be hanging, but clearly its possible to do this since SqlWorkbenchJ can run COPY commands without any problems.

https://stackoverflow.com/questions/50474428/troubleshooting-copy-errors-on-aws-redshift

Was just wondering/hoping if anyone with experience here could take a look at my code and see where I might be going awry...thanks! :-/

**Comment by albfan** [comment]
I suggest you to create a http://sscce.org so anyone can run it and check what's the problem

A failed test somewhere can be useful too.

If you create such one I promise to take a look

**Comment by albfan** [comment]
https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/copy/CopyManager.html

https://github.com/albfan/sqlworkbenchj/blob/dd0be7f37648bfb12d629b130849172e2b9cda44/src/workbench/db/postgres/PgCopyManager.java

https://dba.stackexchange.com/questions/191245/how-do-i-use-the-copy-command-with-jdbc

Hope it helps

**Comment by bitbythecron** [comment]
Nice thank you @albfan I will create an SSCCE very shortly and post it here!

**Comment by bitbythecron** [comment]
Hi @albfan here you go:

https://github.com/bitbythecron/redshift-copy-troubleshooting

Just clone it, add your credentials to the `RedshiftCopy.java` file and then run `./gradlew run` from the terminal (in the root of the project).

I'm very interested to see what you think! Thanks again *enormously* for any-and-all help here!!!

**Comment by bitbythecron** [comment]
**@albfan update:** If figured this out but am still interested in an explanation. The problem was that I was running the code below while also connected to my Redshift cluster from SqlWorkbenchJ (both running on the same laptop). The second I disconnect my SqlWorkbenchJ session and re-run my code, it doesn't hang. **Any ideas as to why?!?**

**Comment by albfan** [comment]
The port is not avaliable?

    $ nc host port

That can simulate something connected to your database, so you cannot connect with other program

**Comment by bitbythecron** [comment]
Sorry, you're suggesting that only one app can connect to a Redshift cluster at any given time?! I can tell you that is *certainly* not the case!!! As I am able to run multiple instances of my app on different nodes, all connecting to the same Redshift cluster (exact hostname + port)!

Or am I misunderstanding you? Thanks again for any insight!

**Comment by bitbythecron** [comment]
I was able to run my code on multiple nodes on AWS EMR while also connected to Redshift from my laptop via SqlWorkbenchJ, so I think this only happens when SqlWorkbenchJ is connected to Redshift and another local process attempts to do the same with the Postgres driver.

I *doubt* this is a bug in the Postgres driver, although anything is certainly possible. But just FYI this community might want to try and reproduce and raise it as a potential bug.

**Comment by albfan** [comment]
I reread all the issue.

This is not the official repo for SQL workbench/J. This is just a git mirror. The project is developed in svn (yes, for real).

I just made a few contributions

You can post a question here:
https://groups.google.com/forum/m/#!forum/sql-workbench

The maintainer is really supportive and both can find the problem and fix it.

**Comment by bitbythecron** [comment]
Oh I'm so sorry! I thought this was the main repo and that you were the main contributor! Mea culpa!!! Thanks for the help though :-)
